-- AlterTable
ALTER TABLE `centros` ADD COLUMN `altitud` INTEGER NULL,
    ADD COLUMN `ambito` VARCHAR(20) NULL,
    ADD COLUMN `banda` VARCHAR(5) NULL,
    ADD COLUMN `codigo_renipress` VARCHAR(20) NULL,
    ADD COLUMN `codigo_ubigeo_distrito` VARCHAR(6) NULL,
    ADD COLUMN `coordenada_este` VARCHAR(20) NULL,
    ADD COLUMN `coordenada_norte` VARCHAR(20) NULL,
    ADD COLUMN `establecimiento_salud` VARCHAR(150) NULL,
    ADD COLUMN `huso` VARCHAR(5) NULL,
    ADD COLUMN `latitud` DOUBLE NULL,
    ADD COLUMN `longitud` DOUBLE NULL,
    ADD COLUMN `nombre_centro_poblado` VARCHAR(150) NULL,
    ADD COLUMN `poblacion_servida` INTEGER NULL,
    ADD COLUMN `poblacion_total` INTEGER NULL,
    ADD COLUMN `poblacion_vigilada` INTEGER NULL,
    ADD COLUMN `quintil` VARCHAR(5) NULL,
    ADD COLUMN `tiene_sistema_agua` BOOLEAN NULL,
    ADD COLUMN `validado_minsa` BOOLEAN NULL;
