ALTER TABLE `reporte_items`
    MODIFY `cloro` DOUBLE NULL,
    MODIFY `conductividad` DOUBLE NULL,
    MODIFY `ph` DOUBLE NULL,
    MODIFY `temperatura` DOUBLE NULL,
    MODIFY `turbiedad` DOUBLE NULL,
    ADD COLUMN `codigo_muestreo` VARCHAR(191) NULL,
    ADD COLUMN `codigo_muestra` VARCHAR(191) NULL,
    ADD COLUMN `coordenada_este` VARCHAR(191) NULL,
    ADD COLUMN `coordenada_norte` VARCHAR(191) NULL,
    ADD COLUMN `huso_banda` VARCHAR(191) NULL,
    ADD COLUMN `altura` VARCHAR(191) NULL,
    ADD COLUMN `estado_muestreo` VARCHAR(191) NULL,
    ADD COLUMN `fecha_muestreo` VARCHAR(191) NULL,
    ADD COLUMN `fecha_finalizado` VARCHAR(191) NULL,
    ADD COLUMN `lugar_muestreo_id` VARCHAR(191) NULL,
    ADD COLUMN `lugar_muestreo_ubicacion` VARCHAR(191) NULL,
    ADD COLUMN `lugar_muestreo_nombre` VARCHAR(191) NULL,
    ADD COLUMN `continuidad_horas_dia` VARCHAR(191) NULL,
    ADD COLUMN `continuidad_dias_semana` VARCHAR(191) NULL,
    ADD COLUMN `decreto_aluminio` VARCHAR(191) NULL,
    ADD COLUMN `decreto_bacterias_coliformes_fecales` VARCHAR(191) NULL,
    ADD COLUMN `decreto_bacterias_coliformes_totales` VARCHAR(191) NULL,
    ADD COLUMN `decreto_bacterias_heterotroficas` VARCHAR(191) NULL,
    ADD COLUMN `decreto_cobre` VARCHAR(191) NULL,
    ADD COLUMN `decreto_cromo_total` VARCHAR(191) NULL,
    ADD COLUMN `decreto_e_coli_nmp` VARCHAR(191) NULL,
    ADD COLUMN `decreto_hierro` VARCHAR(191) NULL,
    ADD COLUMN `decreto_huevos_larvas_helmintos` VARCHAR(191) NULL,
    ADD COLUMN `decreto_manganeso` VARCHAR(191) NULL,
    ADD COLUMN `decreto_nitratos` VARCHAR(191) NULL,
    ADD COLUMN `decreto_nitritos_exposicion_corta` VARCHAR(191) NULL,
    ADD COLUMN `decreto_organismos_vida_libre` VARCHAR(191) NULL,
    ADD COLUMN `decreto_solidos_totales_disueltos` VARCHAR(191) NULL,
    ADD COLUMN `decreto_sulfatos` VARCHAR(191) NULL,
    ADD COLUMN `eca_aluminio` VARCHAR(191) NULL,
    ADD COLUMN `eca_cobre` VARCHAR(191) NULL,
    ADD COLUMN `eca_coliformes_termotolerantes` VARCHAR(191) NULL,
    ADD COLUMN `eca_coliformes_totales` VARCHAR(191) NULL,
    ADD COLUMN `eca_conductividad` VARCHAR(191) NULL,
    ADD COLUMN `eca_cromo_total` VARCHAR(191) NULL,
    ADD COLUMN `eca_escherichia_coli` VARCHAR(191) NULL,
    ADD COLUMN `eca_formas_parasitarias` VARCHAR(191) NULL,
    ADD COLUMN `eca_hierro` VARCHAR(191) NULL,
    ADD COLUMN `eca_manganeso` VARCHAR(191) NULL,
    ADD COLUMN `eca_nitratos` VARCHAR(191) NULL,
    ADD COLUMN `eca_nitritos` VARCHAR(191) NULL,
    ADD COLUMN `eca_organismos_vida_libre` VARCHAR(191) NULL,
    ADD COLUMN `eca_ph` VARCHAR(191) NULL,
    ADD COLUMN `eca_sulfatos` VARCHAR(191) NULL,
    ADD COLUMN `eca_temperatura` VARCHAR(191) NULL,
    ADD COLUMN `eca_turbiedad` VARCHAR(191) NULL;
